/*****************************************************************//**
 * @file   ast.cpp
 * @brief  Contains the implementation of 'ast.h'.
 * 
 * @author RPC
 * @date   April 2024
 *********************************************************************/
#include "ast.h"

namespace clt::lng
{
  void MakeAST(ParsedUnit& unit) noexcept
  {
    if constexpr (isDebugBuild())
    {
      try
      {
        ASTMaker ast = { unit };
      }
      catch (...)
      {

      }
    }
  }

  void ASTMaker::panic_consume_semicolon() noexcept
  {

  }


  ProdExprToken ASTMaker::parse_primary_literal(TokenRange range) noexcept
  {
    assert_true("Expected literal token!", isLiteralToken(current()));
    //Save literal token
    auto literal_tkn = current();

    //Consume the literal token
    consume_current();
    
    //TODO: add support for string literal
    QWORD_t value = getTokenBuffer().getLiteral(literal_tkn);
    return getExprBuffer().addLiteral(
      range, value, LiteralToBuiltinID(literal_tkn)
    );
  }
  
  ProdExprToken ASTMaker::parse_primary_invalid(TokenRange range) noexcept
  {
    using enum Lexeme;
    
    // The error would have been generated by the lexer
    if (current() == TKN_ERROR)
      consume_current();
    else
      report_current<ERROR>(&ASTMaker::panic_consume_semicolon, "Expected an expression!");

    return getExprBuffer().addError(range);
  }

  ProdExprToken ASTMaker::parse_primary(bool accepts_conv)
  {
    using enum Lexeme;
    auto depth = addDepth();
    auto range = startRange();

    uninit<ProdExprToken> to_ret;

    // Handles literals (10, 0.5, ...)
    if (isLiteralToken(current()))
      to_ret = parse_primary_literal(range.getRange());
    // Handles unary operators (&, *, -, ...)
    else if (isUnaryToken(current()))
      to_ret = parse_unary();
    // Handles (...)
    else if (current() == TKN_LEFT_PAREN)
      to_ret = parse_parenthesis(&ASTMaker::parse_binary);
    // Handles invalid primary expressions
    else
      to_ret = parse_primary_invalid(range.getRange());    

    //If the primary expression accepts a conversion, check for as/bit_as.
    if (accepts_conv && is_current_one_of(TKN_KEYWORD_bit_as, TKN_KEYWORD_as))
      return parse_conversion(to_ret, line_state);
    return to_ret;
  }

  ProdExprToken ASTMaker::parse_unary_and(ProdExprToken child, TokenRange range) noexcept
  {
    if (auto pchild = decl_from_read(child); pchild.isValue())
      return getExprBuffer().addAddressOf(range, pchild.getValue());

    report<ERROR>(range, &ASTMaker::panic_consume_semicolon,
      "Unary '&' can only be applied on a variable!");
    return getExprBuffer().addError(range);
  }

  ProdExprToken ASTMaker::parse_unary_star(ProdExprToken child, TokenRange range) noexcept
  {
    if (!getExprBuffer().getType(child).isAnyOpaquePtr())
    {
      report<ERROR>(range, &ASTMaker::panic_consume_semicolon,
        "Unary '*' can only be applied on a non-opaque pointer!");
      return getExprBuffer().addError(range);
    }
    else if (!getExprBuffer().getType(child).isAnyPtr())
    {
      report<ERROR>(range, &ASTMaker::panic_consume_semicolon,
        "Unary '*' can only be applied on pointer types!");
      return getExprBuffer().addError(range);
    }
    return getExprBuffer().addPtrLoad(range, child);
  }

  ProdExprToken ASTMaker::parse_unary()
  {
    using enum Lexeme;
    auto depth = addDepth();
    auto range = startRange();

    uninit<ProdExprToken> to_ret;

    //Save the operator
    Token op = current();
    consume_current(); //consume the unary operator

    //Parse the child expression, without handling conversions:
    // '-5 as i32' is equivalent to '(-5) as i32'
    ProdExprToken child = parse_primary(false);
    if (getExprBuffer().getExpr(child).isError())
      return child;

    switch (op)
    {
    case TKN_PLUS_PLUS:
    case TKN_MINUS_MINUS:
      
      // Handles '+', which are not supported by the language
    break; case TKN_PLUS:
      report<ERROR>(range.getRange(), &ASTMaker::panic_consume_semicolon, "Unary '+' is not supported!");
      to_ret = getExprBuffer().addError(range.getRange());
      
      // Handles '&', which are usually AddressOf expressions
    break; case TKN_AND:    
      to_ret = parse_unary_and(child, range.getRange());    
      
      // Handles '*', which are usually PtrLoad expressions
    break; case TKN_STAR:
      to_ret = parse_unary_star(child, range.getRange());
    
    break; default:
      //if (!child->type()->supports(TokenToUnary(op)))
      //{
      //  generate<ERROR>(line_state.to_src_info(), &ASTMaker::panic_consume_semicolon,
      //    "'{}' does not support '{}' operator!", type_name(ctx, child->type()), op_symbol); //TESTED
      //  to_ret = Expr::CreateError(ctx, line_state.to_src_info());
      //}
      //else
        to_ret = getExprBuffer().addUnary(range.getRange(), TokenToUnary(op), child);
    }
    return to_ret;
  }
  
  OptTok<StmtExprToken> ASTMaker::decl_from_read(ProdExprToken expr) const noexcept
  {
    auto& read = getExprBuffer().getExpr(expr);
    if (!read.isRead())
      return None;
    return read.getExpr<ReadExpr>()->getDecl();
  }
}